on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: WillBailie/dusk-results-action@main
      with:
        report_path: './dusk_output.json'
        github_token: ${{ secrets.GITHUB_TOKEN }}