on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: annotate test failures job
    steps:
    - name: annotate test failures step
      id: dusk
      uses: WillBailie/dusk-results-action@v1