on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: WillBailie/dusk-results-action@v2
      with:
        report_path: './dusk_output.json'